import type { AIModel } from '@/types/studios';
import { isValidApiKey } from './utils';
import { MODELS, openaiImageSize } from './models';
import { PROVIDER_TIMEOUTS, ProviderPermanentError, fetchWithTimeout } from './http';
import { mockFromSchema } from './mock-from-schema';

interface GenerateImageOptions {
  prompt: string;
  resolution: string;
  /** Forwarded to openaiImageSize(), which computes a WIDTHxHEIGHT meeting
   *  gpt-image-2's documented constraints. Omitted means square, which is what
   *  this adapter returned for every caller before it took a ratio. */
  aspectRatio?: string;
}

interface GenerateTextOptions {
  prompt: string;
  maxTokens?: number;
  temperature?: number;
  /**
   * An OpenAPI-3.0-subset schema. When present the request ASKS the model for JSON
   * of this shape instead of hoping that prose written at temperature 0.7 happens
   * to contain a parseable object. The regex scrape at each call site stays in
   * place on purpose, so a model or endpoint that ignores this degrades to the
   * previous behaviour rather than failing.
   */
  responseSchema?: Record<string, unknown>;
}

interface AIResult {
  url?: string;
  text?: string;
  model: AIModel;
  mock: boolean;
}

const MOCK_IMAGE_URLS = [
  'https://placehold.co/1080x1080/4F46E5/FFFFFF?text=GPT+Generated',
  'https://placehold.co/1080x1080/3730A3/FFFFFF?text=GPT+AI',
  'https://placehold.co/1080x1080/818CF8/FFFFFF?text=GPT+Studio',
  'https://placehold.co/1080x1080/A5B4FC/000000?text=GPT+Creative',
];

function getMockImageUrl(): string {
  return MOCK_IMAGE_URLS[Math.floor(Math.random() * MOCK_IMAGE_URLS.length)];
}

export async function generateImage(options: GenerateImageOptions): Promise<AIResult> {
  const apiKey = process.env.OPENAI_API_KEY;

  if (!isValidApiKey(apiKey)) {
    await new Promise((resolve) => setTimeout(resolve, 2000));
    return { url: getMockImageUrl(), model: 'gpt', mock: true };
  }

  const response = await fetchWithTimeout('https://api.openai.com/v1/images/generations', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${apiKey}`,
    },
    body: JSON.stringify({
      model: MODELS.openaiImage,
      prompt: options.prompt,
      n: 1,
      size: openaiImageSize(options.resolution, options.aspectRatio),
      /**
       * PINNED, and the pin is the point of the gpt-image-2.5 adoption.
       *
       * This parameter was absent, so the documented default `"auto"` applied —
       * "automatically select the best quality for the given model". That was
       * survivable while the model's ladder topped out at `high`. gpt-image-2.5
       * adds `xhigh` and `max` above it, at up to $0.211 per 1024x1024 — more
       * than a 4K image earns on three of our four paid plans, and 4-7x what a
       * 1080p image earns on any of them. `auto` on a longer ladder is an
       * uncapped bill that no diff near the money would have shown.
       *
       * `high` is chosen rather than a cheaper tier because it is not a
       * downgrade: 2.5's ladder shifted DOWN against 2's, so 2.5 at `high`
       * bills roughly what gpt-image-2 billed at `medium`. Against the model
       * this replaces we get better output, ~50% lower latency, and a lower
       * cost — while the ceiling stays a named tier we have priced instead of
       * a word OpenAI is free to reinterpret.
       *
       * `scripts/tests/model-registry.test.ts` fails the build if a model whose
       * ceiling is `xhigh` or `max` is ever configured while this line is gone.
       */
      quality: 'high',
    }),
  }, PROVIDER_TIMEOUTS.image, 'gpt');

  if (!response.ok) {
    // Classified, so the retry policy can tell a 503 (worth another attempt) from a
    // 401 (a rotated key — three attempts is three paid failures).
    throw new ProviderPermanentError(`OpenAI API error: ${response.status}`, response.status);
  }

  const data = await response.json();

  // The GPT image models return base64 in `b64_json` by DEFAULT — they only return
  // `url` when response_format:"url" is requested. This code read `.url` only, so
  // it always threw "No image generated" and every request silently fell through
  // to the next provider. Read b64_json first and keep `url` as the fallback.
  const b64 = data.data?.[0]?.b64_json;
  if (b64) {
    return { url: `data:image/png;base64,${b64}`, model: 'gpt', mock: false };
  }

  const imageUrl = data.data?.[0]?.url;
  if (!imageUrl) {
    throw new Error('No image generated by OpenAI');
  }

  return { url: imageUrl, model: 'gpt', mock: false };
}

export async function generateText(options: GenerateTextOptions): Promise<AIResult> {
  const apiKey = process.env.OPENAI_API_KEY;

  if (!isValidApiKey(apiKey)) {
    await new Promise((resolve) => setTimeout(resolve, 1000));
    // Was the literal `{"mock": true}` — valid JSON of the wrong shape for every
    // studio, so it parsed and then failed the Zod check, landing in the same
    // 500 generation_parse_failed branch as gemini's campaign fixture. This is
    // the FALLBACK provider, so with both unconfigured a local run failed twice
    // for two different reasons and reported neither.
    return {
      text: options.responseSchema ? mockFromSchema(options.responseSchema) : '{"mock": true}',
      model: 'gpt',
      mock: true,
    };
  }

  // GPT-5 and the o-series reject `max_tokens` outright:
  //   400 "Unsupported parameter: 'max_tokens' … Use 'max_completion_tokens' instead."
  // They also only accept the default temperature. Older models (gpt-4o and
  // friends) still require the legacy `max_tokens`, so the payload is built to
  // match whichever model is configured — otherwise this fallback path 400s on
  // every request and all nine studios lose their backup provider.
  const model = MODELS.openaiText;
  const isNextGen = /^(gpt-5|o[1-9])/.test(model);

  const body: Record<string, unknown> = {
    model,
    messages: [{ role: 'user', content: options.prompt }],
  };

  if (isNextGen) {
    body.max_completion_tokens = options.maxTokens || 4096;
  } else {
    body.max_tokens = options.maxTokens || 4096;
    // `??`, not `||`: a deliberate temperature of 0 — which is what a
    // schema-constrained request wants — was coerced back to 0.7.
    body.temperature = options.temperature ?? 0.7;
  }

  if (options.responseSchema) {
    // strict:false deliberately. Strict mode demands additionalProperties:false and
    // every property listed in `required`; the schema this shares with the Gemini
    // path satisfies neither, and a 400 here costs all five studios their fallback
    // provider — the same failure shape documented above for max_tokens.
    body.response_format = {
      type: 'json_schema',
      json_schema: { name: 'studio_output', strict: false, schema: options.responseSchema },
    };
  }

  const response = await fetchWithTimeout('https://api.openai.com/v1/chat/completions', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${apiKey}`,
    },
    body: JSON.stringify(body),
  }, PROVIDER_TIMEOUTS.text, 'gpt');

  if (!response.ok) {
    const detail = await response.text().catch(() => '');
    throw new ProviderPermanentError(`OpenAI text API error: ${response.status}${detail ? ` — ${detail.slice(0, 200)}` : ''}`, response.status);
  }

  const data = await response.json();
  const text = data.choices?.[0]?.message?.content;

  if (!text) {
    throw new Error('No text generated by OpenAI');
  }

  return { text, model: 'gpt', mock: false };
}
