import type { AIModel } from '@/types/studios';
import { isValidApiKey } from './utils';

interface GenerateImageOptions {
  prompt: string;
  resolution: string;
}

interface GenerateTextOptions {
  prompt: string;
  maxTokens?: number;
  temperature?: number;
}

interface AIResult {
  url?: string;
  text?: string;
  model: AIModel;
  mock: boolean;
}

const MOCK_IMAGE_URLS = [
  'https://placehold.co/1080x1080/4F46E5/FFFFFF?text=GPT+Generated',
  'https://placehold.co/1080x1080/3730A3/FFFFFF?text=GPT+AI',
  'https://placehold.co/1080x1080/818CF8/FFFFFF?text=GPT+Studio',
  'https://placehold.co/1080x1080/A5B4FC/000000?text=GPT+Creative',
];

function getMockImageUrl(): string {
  return MOCK_IMAGE_URLS[Math.floor(Math.random() * MOCK_IMAGE_URLS.length)];
}

export async function generateImage(options: GenerateImageOptions): Promise<AIResult> {
  const apiKey = process.env.OPENAI_API_KEY;

  if (!isValidApiKey(apiKey)) {
    await new Promise((resolve) => setTimeout(resolve, 2000));
    return { url: getMockImageUrl(), model: 'gpt', mock: true };
  }

  const sizeMap: Record<string, string> = {
    '1080p': '1024x1024',
    '2K': '1024x1536',
    '4K': '1536x1024',
  };

  const response = await fetch('https://api.openai.com/v1/images/generations', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${apiKey}`,
    },
    body: JSON.stringify({
      model: 'gpt-image-1',
      prompt: options.prompt,
      n: 1,
      size: sizeMap[options.resolution] || '1024x1024',
    }),
  });

  if (!response.ok) {
    throw new Error(`OpenAI API error: ${response.status}`);
  }

  const data = await response.json();
  const imageUrl = data.data?.[0]?.url;

  if (!imageUrl) {
    throw new Error('No image generated by OpenAI');
  }

  return { url: imageUrl, model: 'gpt', mock: false };
}

export async function generateText(options: GenerateTextOptions): Promise<AIResult> {
  const apiKey = process.env.OPENAI_API_KEY;

  if (!isValidApiKey(apiKey)) {
    await new Promise((resolve) => setTimeout(resolve, 1000));
    return { text: '{"mock": true}', model: 'gpt', mock: true };
  }

  const response = await fetch('https://api.openai.com/v1/chat/completions', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${apiKey}`,
    },
    body: JSON.stringify({
      model: 'gpt-4o',
      messages: [{ role: 'user', content: options.prompt }],
      max_tokens: options.maxTokens || 4096,
      temperature: options.temperature || 0.7,
    }),
  });

  if (!response.ok) {
    throw new Error(`OpenAI text API error: ${response.status}`);
  }

  const data = await response.json();
  const text = data.choices?.[0]?.message?.content;

  if (!text) {
    throw new Error('No text generated by OpenAI');
  }

  return { text, model: 'gpt', mock: false };
}
