import type { AIModel } from '@/types/studios';
import { isValidApiKey } from './utils';
import { MODELS, openaiImageSize } from './models';

interface GenerateImageOptions {
  prompt: string;
  resolution: string;
}

interface GenerateTextOptions {
  prompt: string;
  maxTokens?: number;
  temperature?: number;
}

interface AIResult {
  url?: string;
  text?: string;
  model: AIModel;
  mock: boolean;
}

const MOCK_IMAGE_URLS = [
  'https://placehold.co/1080x1080/4F46E5/FFFFFF?text=GPT+Generated',
  'https://placehold.co/1080x1080/3730A3/FFFFFF?text=GPT+AI',
  'https://placehold.co/1080x1080/818CF8/FFFFFF?text=GPT+Studio',
  'https://placehold.co/1080x1080/A5B4FC/000000?text=GPT+Creative',
];

function getMockImageUrl(): string {
  return MOCK_IMAGE_URLS[Math.floor(Math.random() * MOCK_IMAGE_URLS.length)];
}

export async function generateImage(options: GenerateImageOptions): Promise<AIResult> {
  const apiKey = process.env.OPENAI_API_KEY;

  if (!isValidApiKey(apiKey)) {
    await new Promise((resolve) => setTimeout(resolve, 2000));
    return { url: getMockImageUrl(), model: 'gpt', mock: true };
  }

  const response = await fetch('https://api.openai.com/v1/images/generations', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${apiKey}`,
    },
    body: JSON.stringify({
      model: MODELS.openaiImage,
      prompt: options.prompt,
      n: 1,
      size: openaiImageSize(options.resolution),
    }),
  });

  if (!response.ok) {
    throw new Error(`OpenAI API error: ${response.status}`);
  }

  const data = await response.json();

  // The GPT image models return base64 in `b64_json` by DEFAULT — they only return
  // `url` when response_format:"url" is requested. This code read `.url` only, so
  // it always threw "No image generated" and every request silently fell through
  // to the next provider. Read b64_json first and keep `url` as the fallback.
  const b64 = data.data?.[0]?.b64_json;
  if (b64) {
    return { url: `data:image/png;base64,${b64}`, model: 'gpt', mock: false };
  }

  const imageUrl = data.data?.[0]?.url;
  if (!imageUrl) {
    throw new Error('No image generated by OpenAI');
  }

  return { url: imageUrl, model: 'gpt', mock: false };
}

export async function generateText(options: GenerateTextOptions): Promise<AIResult> {
  const apiKey = process.env.OPENAI_API_KEY;

  if (!isValidApiKey(apiKey)) {
    await new Promise((resolve) => setTimeout(resolve, 1000));
    return { text: '{"mock": true}', model: 'gpt', mock: true };
  }

  // GPT-5 and the o-series reject `max_tokens` outright:
  //   400 "Unsupported parameter: 'max_tokens' … Use 'max_completion_tokens' instead."
  // They also only accept the default temperature. Older models (gpt-4o and
  // friends) still require the legacy `max_tokens`, so the payload is built to
  // match whichever model is configured — otherwise this fallback path 400s on
  // every request and all nine studios lose their backup provider.
  const model = MODELS.openaiText;
  const isNextGen = /^(gpt-5|o[1-9])/.test(model);

  const body: Record<string, unknown> = {
    model,
    messages: [{ role: 'user', content: options.prompt }],
  };

  if (isNextGen) {
    body.max_completion_tokens = options.maxTokens || 4096;
  } else {
    body.max_tokens = options.maxTokens || 4096;
    body.temperature = options.temperature || 0.7;
  }

  const response = await fetch('https://api.openai.com/v1/chat/completions', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${apiKey}`,
    },
    body: JSON.stringify(body),
  });

  if (!response.ok) {
    const detail = await response.text().catch(() => '');
    throw new Error(`OpenAI text API error: ${response.status}${detail ? ` — ${detail.slice(0, 200)}` : ''}`);
  }

  const data = await response.json();
  const text = data.choices?.[0]?.message?.content;

  if (!text) {
    throw new Error('No text generated by OpenAI');
  }

  return { text, model: 'gpt', mock: false };
}
