import type { AIModel } from '@/types/studios';
import { isValidApiKey } from './utils';

interface GenerateFluxOptions {
  prompt: string;
  resolution: string;
}

interface AIResult {
  url?: string;
  model: AIModel;
  mock: boolean;
}

const MOCK_IMAGE_URLS = [
  'https://placehold.co/1080x1080/0891B2/FFFFFF?text=Flux+Generated',
  'https://placehold.co/1080x1080/22D3EE/000000?text=Flux+AI',
  'https://placehold.co/1080x1080/67E8F9/000000?text=Flux+Studio',
];

function getMockImageUrl(): string {
  return MOCK_IMAGE_URLS[Math.floor(Math.random() * MOCK_IMAGE_URLS.length)];
}

export async function generateFlux(options: GenerateFluxOptions): Promise<AIResult> {
  const apiToken = process.env.REPLICATE_API_TOKEN;

  if (!isValidApiKey(apiToken)) {
    await new Promise((resolve) => setTimeout(resolve, 2500));
    return { url: getMockImageUrl(), model: 'flux', mock: true };
  }

  const sizeMap: Record<string, { width: number; height: number }> = {
    '1080p': { width: 1024, height: 1024 },
    '2K': { width: 1440, height: 1440 },
    '4K': { width: 2048, height: 2048 },
  };

  const size = sizeMap[options.resolution] || sizeMap['1080p'];

  // Start prediction
  const createResponse = await fetch('https://api.replicate.com/v1/predictions', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${apiToken}`,
    },
    body: JSON.stringify({
      model: 'black-forest-labs/flux-1.1-pro',
      input: {
        prompt: options.prompt,
        width: size.width,
        height: size.height,
      },
    }),
  });

  if (!createResponse.ok) {
    throw new Error(`Replicate API error: ${createResponse.status}`);
  }

  const prediction = await createResponse.json();
  let result = prediction;

  // Poll for completion (max 60 seconds)
  const maxAttempts = 30;
  for (let i = 0; i < maxAttempts; i++) {
    if (result.status === 'succeeded') break;
    if (result.status === 'failed') throw new Error('Flux generation failed');

    await new Promise((resolve) => setTimeout(resolve, 2000));

    const pollResponse = await fetch(
      `https://api.replicate.com/v1/predictions/${result.id}`,
      {
        headers: { Authorization: `Bearer ${apiToken}` },
      }
    );

    result = await pollResponse.json();
  }

  const outputUrl = Array.isArray(result.output) ? result.output[0] : result.output;

  if (!outputUrl) {
    throw new Error('No image generated by Flux');
  }

  return { url: outputUrl as string, model: 'flux', mock: false };
}
